sinclude ../Makefile

SRCS = check_word_type.c \
get_segment.c \
read_line.c \
linked_list.c \
open_file.c \
registers.c \
data_handler.c \
string_handler.c \
inst_0_operands.c inst_1_operands.c inst_2_operands.c \
build_words_array.c \
clean_memory_image.c


build: $(SRCS)
	$(CC) $(FLAGS) -c $^
